### ISSUE TITLE
How to use with Firefox

### ISSUE THREAD

**Issue by AnthonMS** [gissehel/BarLauncher-WebApp#3]
Great work, love the plugin! But I'm having some trouble to get it working with firefox after swithcing all devices to that browser because of privacy concerns in Google and MS products.

I am trying to set this up so it can open web apps in firefox. But I, for some reason, cannot get it to work with that browser.

I have gotten it to work with edge and chrome by running these commands:
wap config default msedge.exe --app="{0}" --profile-directory="Default"
wap config chrome chrome.exe --app="{0}" --profile-directory="Default"

So when I add an entry under config default, then it will open the web app in Edge as a new window, as expected.
The same for the chrome browser. Open correctly in chrome and open it in a new window without all the URL and bookmark stuff in the top.

But if I try to add firefox as a config instead, then i get some weird behavior. 

If I create the firefox config like the this:
```wap config firefox firefox.exe --app="{0}" --profile-directory="Default"```
Then when I create an app shortcut for this config and open the app, then it will just open a new Firefox window without any tabs open. And it just opens the browser, not a "web app" window without URL and bookmark bar.

If I create firefox config like this:
```wap config firefox firefox.exe "{0}" --profile-directory="Default"```
Then it opens the correct website, but it open it as a tab in an already active firefox window.

How do I get it to open a single web app window in firefox like with Edge and Chrome?

**Comment by gissehel** [comment]
Hello,

Indeed, firefox doesn't support "webapp" mode at all.

the reason why msedge support it, and support it the same way than chrome is not because it's a standard, but just because msedge is based on chromium (the one source project that powers chrome), like chrome, and they both share the same command line options.

Firefox is not based on chromium. And despite some people asking for a "webapp mode" on firefox for more than 10 years, firefox refuses to implement that, thus it's not possible. Having the page opened in a tab is the best thing you can do (and you seems to have find it already).

There once was a standalone binary based on firefox source that was able to start a page in webapp mode, but support for that was dropped long long time ago (between the switch from firefox 3.6 and firefox 4 if I remember correctly)

To address your concerns about privacy, what I can recommand are projects based on chromium (like chrome or msedge) but focused on privacy. It appears there are several of them due to the bad image of Google. For example:
- Vivaldi (not tested but should work in theory)
- Brave (tested and works like Chrome or msedge)

**Comment by AnthonMS** [comment]
Thank you very much for your detailed explanation. I suspected it was because both MSEdge and Chrome was chromium. 

I just thought maybe firefox also supported web apps on the pc since they support it on the phone. But that is entirely different of course.

Thanks for the suggestions. I have used Brave back when it started out, but it was very buggy back then. Maybe I should try it out to see if it has improved in the past years.

Cheers!
